// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/arikama/koran-backend/daos"
	"github.com/arikama/koran-backend/managers"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func wireUserDaoImpl() (*daos.UserDaoImpl, error) {
	db, err := NewDb()
	if err != nil {
		return nil, err
	}
	userDaoImpl, err := daos.NewUserDaoImpl(db)
	if err != nil {
		return nil, err
	}
	return userDaoImpl, nil
}

func wireGoogleAuthManagerImpl() (*managers.GoogleAuthManagerImpl, error) {
	db, err := NewDb()
	if err != nil {
		return nil, err
	}
	userDaoImpl, err := daos.NewUserDaoImpl(db)
	if err != nil {
		return nil, err
	}
	googleAuthManagerImpl, err := managers.NewGoogleAuthManagerImpl(userDaoImpl)
	if err != nil {
		return nil, err
	}
	return googleAuthManagerImpl, nil
}

func wireQuranManagerImpl(csvDir string) (*managers.QuranManagerImpl, error) {
	quranManagerImpl, err := managers.NewQuranManagerImpl(csvDir)
	if err != nil {
		return nil, err
	}
	return quranManagerImpl, nil
}
