// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/arikama/koran-backend/managers"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeQuranManagerImpl(csvDir string) (*managers.QuranManagerImpl, error) {
	quranManagerImpl, err := managers.NewQuranManagerImpl(csvDir)
	if err != nil {
		return nil, err
	}
	return quranManagerImpl, nil
}

func InitializeGoogleAuthManagerImpl() (*managers.GoogleAuthManagerImpl, error) {
	googleAuthManagerImpl, err := managers.NewGoogleAuthManagerImpl()
	if err != nil {
		return nil, err
	}
	return googleAuthManagerImpl, nil
}
