# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go build -v ./...
      - run: go test -v ./...
