# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: coverage
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - run: go build -v ./...
      - run: go test -v -coverprofile=coverage.txt ./...
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
